"""Deterministic Lightroom-compatible XMP sidecar export."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

from .actions import ActionError, policy_clusters
from .reviews import ReviewStore


LABEL_NAMES = {
    "": "",
    "red": "Red",
    "yellow": "Yellow",
    "green": "Green",
    "blue": "Blue",
    "purple": "Purple",
}


def _xmp(name: str, annotation: dict, selected: bool) -> bytes:
    rating = int(annotation.get("rating", 0))
    flag = annotation.get("flag", "unrated")
    pick = -1 if flag == "reject" else 1 if (flag == "keep" or selected) else 0
    label = LABEL_NAMES.get(annotation.get("label", ""), "")
    subject = "OpenCull Maybe" if flag == "maybe" else ""
    xml = f"""<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
   xmlns:xmp="http://ns.adobe.com/xap/1.0/"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:opencull="https://opencull.local/ns/1.0/"
   xmp:Rating="{rating}" xmp:Label="{escape(label)}"
   opencull:Pick="{pick}" opencull:Source="{escape(name)}">
   <dc:subject><rdf:Bag><rdf:li>{escape(subject)}</rdf:li></rdf:Bag></dc:subject>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
"""
    return xml.encode("utf-8")


def xmp_zip(review: ReviewStore, policy: str) -> tuple[bytes, str]:
    clusters = policy_clusters(review, policy)
    annotations = {
        name: annotation
        for cluster in review.export()["clusters"]
        for name, annotation in cluster.get("photo_annotations", {}).items()
    }
    output = io.BytesIO()
    used: set[str] = set()
    with zipfile.ZipFile(
        output, "w", compression=zipfile.ZIP_DEFLATED
    ) as archive:
        for cluster in clusters:
            selected = set(cluster["keepers"])
            for name in cluster["photos"]:
                path = Path(name)
                sidecar = path.with_suffix(".xmp").as_posix()
                if sidecar in used:
                    raise ActionError(f"duplicate XMP destination: {sidecar}")
                used.add(sidecar)
                archive.writestr(
                    sidecar,
                    _xmp(name, annotations.get(name, {}), name in selected),
                )
        archive.writestr(
            "OPENCULL-XMP-NOTICE.txt",
            "Generated by OpenCull. Original photographs were not modified.\n"
            "Pick is stored in the opencull namespace; Rating and Label use "
            "standard XMP fields.\n",
        )
    return output.getvalue(), "opencull-lightroom-xmp.zip"
